name: Deploy GitHub Pages

# 触发条件：在 push 到 main/master 分支后，新的 Github 项目 应该都是 main，而之前的项目一般都是 master
on:
  push:
    branches:
      - main

# 任务
jobs:
  build-and-deploy:
    # 服务器环境：最新版 Ubuntu
    runs-on: ubuntu-latest
    steps:
      # 拉取代码
      - name: Checkout
        uses: actions/checkout@master

      # 生成静态文件
      - name: Build
        run: npm install && npm run docs:build

      # 部署到 GitHub Pages
      - name: Deploy
        uses: wyqsky/blog@main
        with:
          ACCESS_TOKEN: ${{ secrets.DEPLOY_ACCESS_TOKEN }} # 也就是我们刚才生成的 secret
          BRANCH: release # 部署到指定分支
          FOLDER: dist # vuepress 生成的静态文件存放的地方
